spring.application.name=careerguidance

# Cấu hình đường dẫn lưu file dữ liệu SQLite cục bộ
spring.datasource.url=jdbc:sqlite:career_guidance.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# Chỉ định Hibernate dịch ngôn ngữ truy vấn sang chuẩn SQLite
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Tự động đồng bộ hóa/tạo các bảng dữ liệu từ Code Java vào SQLite
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true